import './globals.css';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <header>
          <h1>Next.js 13 + Sanity</h1>
        </header>

        {children}
      </body>
    </html>
  );
}
