name: Import dataset for cloned project

on:
  workflow_dispatch:
    inputs:
      sanity-project-id:
        required: true
        type: string
      sanity-project-dataset:
        required: true
        type: string

jobs:
  import-dataset:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ inputs.sanity-project-id }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ inputs.sanity-project-dataset }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: pnpm install
      - run: pnpx sanity debug
      - run: echo ${{ env }}
