name: Upload data to sanity project

on:
  workflow_dispatch:
    inputs:
      sanity-project-id:
        required: true
        type: string
      sanity-project-dataset:
        required: true
        type: string

jobs:
  upload-data:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ inputs.sanity-project-id }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ inputs.sanity-project-dataset }}
    name: Upload data
    steps:
      - uses: actions/checkout@v4
      - name: Upload dataset
        uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: . dataset list
          #  dataset import prod-copy.tar.gz production
          # args: . dataset import prod-copy.tar.gz production
      - name: Add sanity webhook
        run: echo "Add sanity webhook"
