name: Import dataset for cloned project

on:
  workflow_call:
    inputs:
      sanity-project-id:
        required: true
        type: string
      sanity-project-dataset:
        required: true
        type: string
    secrets:
      sanity-write-token:
        required: true

jobs:
  import-dataset:
    runs-on: ubuntu-latest
    env:
      SANITY_PERSONAL_AUTH_TOKEN: ${{ secrets.sanity-write-token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g sanity
      - run: echo ${{ inputs.sanity-project-id }} ${{ inputs.sanity-project-dataset }} $env.SANITY_PERSONAL_AUTH_TOKEN
